Fix build issues on Ubuntu 17.10 against latest FFmpeg snapshot
libmir/dcv pull request #120
Opened 2017-12-02 23:15 UTC by carun

2017-12-03 08:01 UTC, ljubobratovicrelja requested changes
Hej @carun thanks for this! Beside the comment on ffmpeg-d version in the dub.json, can you address the issues that are occurring in travis? Can you tell us what is actually going on there?

2017-12-03 08:01 UTC, ljubobratovicrelja commented on dub.json
> +                "ffmpeg-d": "~master"
Why not link to [3.1.0](https://code.dlang.org/packages/ffmpeg-d)? It should contain changes that are currently at master afaik. If that is the case, please change `master` --> `3.1.0`.

2017-12-04 17:33 UTC, carun commented on dub.json
> +                "ffmpeg-d": "~master"
Hi @ljubobratovicrelja, I didn't know which version to use, so I used `master`. Will update to use `3.1.0`.

I'm testing with LDC 1.6.0 and DMD 2.077.1 on my local. Regarding travis failures, do we need to support all the old versions? They are almost > 8 months old. Please confirm.

2017-12-04 22:40 UTC, ljubobratovicrelja commented on dub.json
> +                "ffmpeg-d": "~master"
> Regarding travis failures, do we need to support all the old versions? They are almost > 8 months old

Fair point. In that case, would you be so kind and edit .travis.yml to test newer versions of both compilers? I hope DMD >= 2.0.74.1 and LDC >= 1.4.0 (same front-end as dmd 2.0.74.1) and  will pass alright. Don't worry if you'd prefer not to do it, just say the word. I'll deal with it right after the merge.

2017-12-06 05:51 UTC, carun commented on dub.json
> +                "ffmpeg-d": "~master"
Sure, let me try it.

2017-12-06 06:24 UTC, carun commented on dub.json
> +                "ffmpeg-d": "~master"
Not sure why travis build fails even after the change. @ljubobratovicrelja could you tell me more?

2017-12-06 07:54 UTC, ljubobratovicrelja commented on dub.json
> +                "ffmpeg-d": "~3.1.0"
Maybe try `"ffmpeg-d": "~>3.1.0"` (missing the `>` sign)?

2017-12-06 16:15 UTC, ljubobratovicrelja approved these changes

2017-12-06 16:16 UTC, ljubobratovicrelja commented
Nice! Can we merge?

2017-12-06 17:22 UTC, carun commented
If you say so! 👍

2017-12-07 17:34 UTC, merged